### ISSUE TITLE
Is there a way to preview the rendering of the theme?

### ISSUE THREAD

**Issue by Natim** [FirefoxUX/photon-themes#5]
I made some changes to the theme less files but I don't know if the rendering is good enough. Is there a way to try it?

**Comment by andymikulski** [comment]
I have a living style guide working locally - essentially a clone of http://ant.design/ but wired into using `photon-ant`. It's mostly ready for integration, I will make it a priority to get it up on this repo!

**Comment by donmilla** [comment]
![fb_img_15747637740582](https://user-images.githubusercontent.com/59391026/71626043-281aa380-2bb9-11ea-8dc0-45fd08048682.jpg) loho
